name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
        
    - name: Run tests
      run: |
        uv run pytest tests/ -v --cov=src --cov-report=term-missing
        
    - name: Build Docker image
      run: |
        docker build -t sarcastic-bot .
        
    - name: Test Docker image
      run: |
        echo "TELEGRAM_BOT_TOKEN=test_token" > .env.test
        echo "OPENROUTER_API_KEY=test_key" >> .env.test
        timeout 10s docker run --env-file .env.test sarcastic-bot || true
